pipeline {
    agent {
        docker {
            image 'node:10-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'RUN npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'npm run test'
            }

                }
            
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
